version: '3.1'
services:
  app:
    build: ./django_project
    volumes:
      - ./django_project:/app
    environment:
      - PORT=8000
      - "DJANGO_DEBUG=True"
      - "EMAIL_HOST="
      - "EMAIL_HOST_USER="
      - "EMAIL_HOST_PASSWORD="
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  redis:
      image: redis:alpine
      restart: always
      expose:
        - '6379'
      ports:
        - '6379:6379'
  nginx:
    container_name: nginx
    image: nginx:latest
    volumes: 
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 80:8000

volumes:
  postgres_data: