version: '3.1'
services:
  app:
    build: ./django_project
    volumes:
      - ./django_project:/app
    environment:
      - PORT=8000
      - "DJANGO_DEBUG=True"
    depends_on:
      - db
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes: 
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    ports:
      - 80:8000

volumes:
  postgres_data: